Merge master H(bb) ntuples
sidnarayanan/PandaAnalysis pull request #102
Opened 2018-06-13 17:38 UTC by DylanHsu

2018-06-13 18:05 UTC, DylanHsu commented
with the ad-hoc nominal jet pt fix:
```root [1] events->Scan("jotPt:nJot:nJotMax")
***********************************************************
*    Row   * Instance *     jotPt *      nJot *   nJotMax *
***********************************************************
*        0 *        0 * 45.064304 *         3 *         4 *
*        0 *        1 * 22.115665 *         3 *         4 *
*        0 *        2 * 21.369323 *         3 *         4 *
*        0 *        3 * 17.484472 *         3 *         4 *
*        1 *        0 * 96.864944 *         5 *         8 *
*        1 *        1 * 55.299877 *         5 *         8 *
*        1 *        2 * 50.516391 *         5 *         8 *
*        1 *        3 * 45.942451 *         5 *         8 *
*        1 *        4 * 29.488508 *         5 *         8 *
*        1 *        5 * 29.488508 *         5 *         8 *
*        1 *        6 * 19.684864 *         5 *         8 *
*        1 *        7 * 12.955325 *         5 *         8 *
*        2 *        0 * 236.08477 *         8 *         9 *
*        2 *        1 * 171.67314 *         8 *         9 *
*        2 *        2 * 128.02024 *         8 *         9 *
*        2 *        3 * 80.886383 *         8 *         9 *
*        2 *        4 * 57.583549 *         8 *         9 *
*        2 *        5 * 34.143867 *         8 *         9 *
*        2 *        6 * 33.300884 *         8 *         9 *
*        2 *        7 * 33.921936 *         8 *         9 *
*        2 *        8 * 16.652719 *         8 *         9 *
*        3 *        0 * 97.253318 *         2 *         2 *
*        3 *        1 * 53.848445 *         2 *         2 *
*        4 *        0 * 89.832672 *         4 *         5 *
*        4 *        1 * 63.308261 *         4 *         5 *
```

without the ad-hoc nominal jet pt fix:

```***********************************************************
*    Row   * Instance *     jotPt *      nJot *   nJotMax *
***********************************************************
*        0 *        0 * 45.064304 *         3 *         4 *
*        0 *        1 * 22.115665 *         3 *         4 *
*        0 *        2 * 21.369323 *         3 *         4 *
*        0 *        3 *       -99 *         3 *         4 *
*        1 *        0 * 96.864944 *         5 *         8 *
*        1 *        1 * 55.299877 *         5 *         8 *
*        1 *        2 * 50.516391 *         5 *         8 *
*        1 *        3 * 45.942451 *         5 *         8 *
*        1 *        4 * 29.488508 *         5 *         8 *
*        1 *        5 *       -99 *         5 *         8 *
*        1 *        6 *       -99 *         5 *         8 *
*        1 *        7 *       -99 *         5 *         8 *
*        2 *        0 * 236.08477 *         8 *         9 *
*        2 *        1 * 171.67314 *         8 *         9 *
*        2 *        2 * 128.02024 *         8 *         9 *
*        2 *        3 * 80.886383 *         8 *         9 *
*        2 *        4 * 57.583549 *         8 *         9 *
*        2 *        5 * 34.143867 *         8 *         9 *
*        2 *        6 * 33.300884 *         8 *         9 *
*        2 *        7 * 33.921936 *         8 *         9 *
*        2 *        8 *       -99 *         8 *         9 *
*        3 *        0 * 97.253318 *         2 *         2 *
*        3 *        1 * 53.848445 *         2 *         2 *
*        4 *        0 * 89.832672 *         4 *         5 *
*        4 *        1 * 63.308261 *         4 *         5 *
```

2018-06-13 18:12 UTC, DylanHsu commented
The ad hoc fix is also not correct for jets beyond `nJot` due to the potential change in ordering in different JES scenarios. See example in row 1 of last message. Finding a real fix now.

2018-06-13 21:27 UTC, sidnarayanan commented
This PR needs work.

2018-06-13 21:28 UTC, sidnarayanan commented
Also I think you did `git add *` at some point when merging changes and checked in a bunch of deleted code. Undo that as well.

2018-06-19 19:34 UTC, sidnarayanan requested changes

2018-06-19 19:34 UTC, sidnarayanan commented on Flat/interface/JetsMods.h
> -          csvL = 0.5426; csvM = 0.8484;
Can't change these WPs.

2018-06-19 19:34 UTC, sidnarayanan commented on Flat/src/BTagTools.cc
> -        else
Stop breaking my analyses.

2018-06-19 19:34 UTC, sidnarayanan commented on Flat/src/CommonMods.cc
> +    //  checkEle32();
If unused, delete instead of comment.

2018-06-19 19:34 UTC, sidnarayanan commented on Flat/src/JetsMods.cc
> +      float csv = centralOnly(jet.deepCSVb + jet.deepCSVbb, aeta);
Again.

2018-06-19 19:34 UTC, sidnarayanan commented on Flat/src/Module.cc
> +      //  bl.push_back("triggerObjects");
Delete.

2018-06-19 19:34 UTC, sidnarayanan commented on Flat/test/test.py
> +#a.processType = root.pa.kW
Delete.

2018-06-19 19:34 UTC, sidnarayanan commented on T3/bin/buildMergedInputs.sh
> +  tar --exclude-vcs -chzf cmssw.tgz src/Panda* python biglib bin lib objs test external # h = --dereference symlinks
C'mon dude.

2018-06-19 19:34 UTC, sidnarayanan commented on T3/merging/bigsamples.sh
> +#threshold=4718592 # 4.5 GB
What's the purpose of checking this in if we have another tool to the same thing?

2018-06-19 19:34 UTC, sidnarayanan commented on T3/merging/merge.py
> +#make_chunks = True
Delete.

2018-06-19 19:34 UTC, sidnarayanan commented on T3/merging/merge.py
> +    checkSizeCmd = "du -c {0}/{1}_*.root|grep total|sed 's/\t\+total//g'".format(environ['SUBMIT_OUTDIR'],pd)
Please rewrite.

2018-06-19 19:34 UTC, sidnarayanan commented on T3/merging/merge.py
> +    merged_dir = '/%s/%s/merged/%s/'%(disk, user, submit_name)
What happens if these don't exist?

2018-06-19 19:34 UTC, sidnarayanan commented on T3/merging/merge.py
> +  Load('splitPandaExpress')
Where is this being loaded from?

2018-06-19 19:35 UTC, DylanHsu commented on Flat/interface/JetsMods.h
> -          csvL = 0.5426; csvM = 0.8484;
already fixed

2018-06-19 20:29 UTC, DylanHsu commented
I removed the chunking code from the merger, and made the disk decision more python esque

2018-07-06 17:18 UTC, sidnarayanan approved these changes

2018-07-06 17:19 UTC, merged